"""AI 各模式的输出协议（输出格式 + 模式硬约束 + 占位符注入点）。

选段协议与 ai_selector 的解析器（_suggest_koubo/_normalize_topics/_normalize_remix）
对应，质检协议与 quality.ai_review 的解析器对应。字段名、取值和 id 规则改动
必须与解析代码同步，因此不放进用户可编辑的提示词文件，由系统在运行时拼接。
"""

MODE_PROTOCOLS = {
    'koubo_tighten': '## 输出格式\n\n只输出一个 JSON object：\n\n```json\n{\n  "mode": "koubo_tighten",\n  "summary": "一两句话说明整体取舍思路",\n  "decisions": [\n    {\n      "segment_id": "sentence_0001",\n      "keep": true,\n      "reason": "开场即抛出核心观点",\n      "labels": ["hook"]\n    },\n    {\n      "segment_id": "sentence_0002",\n      "keep": false,\n      "reason": "与上一句重复",\n      "labels": ["repeat"]\n    }\n  ]\n}\n```\n\n- `decisions` 必须覆盖输入的**每一个** `segment_id`，不得遗漏、不得新增。\n- `labels` 可选值：`hook`（开场钩子）、`insight`（核心观点）、`golden_quote`（金句）、`case`（案例/数据）、`method`（方法步骤）、`transition`（必要过渡）、`filler`（口水话）、`repeat`（重复）、`smalltalk`（寒暄）、`broken`（说错/半句）、`asr_suspect`（疑似识别错误）。\n- `reason` 用一句话说清依据，人工复核时要能看懂。\n\n## 硬约束\n\n1. 只能引用输入中已有的 `segment_id`，禁止编造。\n2. 禁止输出任何时间戳。\n3. 只输出 JSON，不要有任何其他文字。\n\n{{USER_BRIEF}}\n',
    'topic_slicing': '## 输出格式\n\n只输出一个 JSON object：\n\n```json\n{\n  "mode": "topic_slicing",\n  "overview": "一两句话概括整条视频讲了什么",\n  "topics": [\n    {\n      "topic_id": "topic_01",\n      "title": "为什么你的第一版产品应该是丑的",\n      "summary": "用两三句话概括该主题的内容",\n      "segment_ids": ["sentence_0004", "sentence_0005", "sentence_0006"],\n      "best_clip": {\n        "segment_ids": ["sentence_0005", "sentence_0006"],\n        "skipped_segment_ids": [],\n        "hook_segment_id": "sentence_0005",\n        "reason": "观点反常识，有具体案例支撑，可独立成片"\n      }\n    }\n  ],\n  "unassigned_segment_ids": ["sentence_0001"]\n}\n```\n\n- `topics[].segment_ids`：该主题覆盖的全部句子（按原文顺序）。\n- `best_clip.segment_ids`：建议成片保留的句子（按原文顺序，必须是该主题的子集）。\n- `hook_segment_id`：切片中最适合当开头的一句（必须在 best_clip 内）。\n- 每个 `segment_id` 至多归属一个主题。\n\n## 硬约束\n\n1. 只能引用输入中已有的 `segment_id`，禁止编造。\n2. 禁止输出任何时间戳；时长只按字数估算，不要输出秒数字段。\n3. 只输出 JSON，不要有任何其他文字。\n\n{{USER_BRIEF}}\n',
    'highlight_remix': '- 成片目标时长：{{TARGET_DURATION}}（未指定时按 30~90 秒设计）。\n\n## 输出格式\n\n只输出一个 JSON object：\n\n```json\n{\n  "mode": "highlight_remix",\n  "golden_quotes": [\n    {"segment_id": "sentence_0012", "quote": "原句文字", "strength": 5, "reason": "反常识+可独立传播"}\n  ],\n  "clips": [\n    {"purpose": "hook", "segment_ids": ["sentence_0012"], "note": "金句前置"},\n    {"purpose": "body", "segment_ids": ["sentence_0003", "sentence_0004", "sentence_0007"], "note": "论证主干"},\n    {"purpose": "echo", "segment_ids": ["sentence_0012"], "note": "结尾重复强调"}\n  ],\n  "title_suggestions": ["可用作视频号标题的两三个候选"]\n}\n```\n\n- `clips` 的顺序就是成片播放顺序（这是本模式与其他模式的核心差异：**允许打乱原文顺序**）。\n- `purpose` 只能是 `hook` / `body` / `echo`；`body` 可以有多条。\n- `strength` 为 1~5 的整数，5 最强。\n- 同一 `segment_id` 允许出现在 hook 和 echo 两处（重复播放），但 body 内不得重复。\n\n## 硬约束\n\n1. 只能引用输入中已有的 `segment_id`，禁止编造。\n2. 禁止输出任何时间戳。\n3. 只输出 JSON，不要有任何其他文字。\n\n{{USER_BRIEF}}\n',
    'quality_review': '\n\n## 输出格式\n\n只输出一个 JSON object：\n\n```json\n{\n  "findings": [\n    {\n      "segment_id": "sentence_0055",\n      "span_text": "超导",\n      "verdict": "auto_fix",\n      "replacement": "超脑",\n      "reason": "上下文讲机构名，已知词表含（超脑）",\n      "confidence": 0.95\n    }\n  ]\n}\n```\n\n- `verdict` 只能是 `auto_fix`（确定是识别错误且给出替换）/ `ask_user`（大概率有问题但需人工决定）/ `ok`（复核后无问题）。\n- `span_text` 必须与输入中『』标注的存疑片段逐字一致；`replacement` 在 auto_fix/ask_user 时提供。\n- `confidence` 为 0~1 的小数，表示你对该判断的把握。\n\n## 硬约束\n\n1. 只能针对输入中标注的存疑片段输出 finding，禁止扩大范围。\n2. 禁止输出任何时间戳；禁止改动句子结构，只做词语级替换建议。\n3. 只输出 JSON，不要有任何其他文字。\n\n{{USER_BRIEF}}\n',
}
